services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: production
    env_file:
      - apps/auth/.env
    depends_on:
      - mongo
    ports:
      - 3000:3000
  todo:
    build:
      context: .
      dockerfile: apps/todo/Dockerfile
      target: production
    env_file:
      - apps/todo/.env
    depends_on:
      - mongo
    ports:
      - 3001:3001
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017